#!/usr/bin/env python3
"""
vokk_runtime_lang.py — early VOKK backend/runtime language layer.

This is not a full runtime replacement. It lets VOKK describe backend/server
surfaces in its own language and compile them into inspectable plans and host
stubs.

Supported top-level blocks:
  app NAME { ... }
  route NAME { ... }
  store NAME { ... }
  session NAME { ... }
  action NAME { ... }
  component NAME { ... }
"""

from __future__ import annotations

import html
import json
import re
from typing import Any, Dict, List


RUNTIME_KINDS = ("app", "route", "store", "session", "action", "component")


def _tokens(line: str) -> List[str]:
    return re.findall(r'"[^"]*"|\S+', line.strip())


def _clean(v: str) -> str:
    return v.strip().strip('"').strip("'")


def _extract_runtime_blocks(source: str) -> List[Dict[str, str]]:
    blocks: List[Dict[str, str]] = []
    n = len(source)
    pattern = r"\b(" + "|".join(RUNTIME_KINDS) + r")\s+([A-Za-z_]\w*)\s*\{"
    for m in re.finditer(pattern, source, re.M):
        kind, name = m.group(1), m.group(2)
        depth, j = 1, m.end()
        while j < n and depth:
            depth += (source[j] == "{") - (source[j] == "}")
            j += 1
        blocks.append({"kind": kind, "name": name, "body": source[m.end():j - 1]})
    return blocks


def _parse_body(body: str) -> Dict[str, Any]:
    spec: Dict[str, Any] = {"raw_lines": []}
    for raw in body.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        spec["raw_lines"].append(line)
        t = _tokens(line)
        key = t[0].lower()
        vals = [_clean(v) for v in t[1:]]
        if not vals:
            spec[key] = True
        elif len(vals) == 1:
            spec[key] = vals[0]
        else:
            spec[key] = vals
    return spec


def parse_runtime_source(source: str) -> Dict[str, Any]:
    blocks = _extract_runtime_blocks(source)
    apps: List[Dict[str, Any]] = []
    routes: List[Dict[str, Any]] = []
    stores: List[Dict[str, Any]] = []
    sessions: List[Dict[str, Any]] = []
    actions: List[Dict[str, Any]] = []
    components: List[Dict[str, Any]] = []
    for b in blocks:
        row = {"kind": b["kind"], "name": b["name"], "spec": _parse_body(b["body"])}
        if b["kind"] == "app":
            apps.append(row)
        elif b["kind"] == "route":
            routes.append(row)
        elif b["kind"] == "store":
            stores.append(row)
        elif b["kind"] == "session":
            sessions.append(row)
        elif b["kind"] == "action":
            actions.append(row)
        elif b["kind"] == "component":
            components.append(row)
    return {
        "apps": apps,
        "routes": routes,
        "stores": stores,
        "sessions": sessions,
        "actions": actions,
        "components": components,
        "counts": {
            "apps": len(apps),
            "routes": len(routes),
            "stores": len(stores),
            "sessions": len(sessions),
            "actions": len(actions),
            "components": len(components),
        },
    }


def _py_list(v: Any) -> str:
    if isinstance(v, list):
        return "[" + ", ".join(repr(x) for x in v) + "]"
    if v is None:
        return "None"
    return repr(v)


def emit_runtime_python(parsed: Dict[str, Any]) -> str:
    lines = [
        "# Generated by VOKK runtime compiler preview",
        "APP = {",
    ]
    app = parsed["apps"][0] if parsed["apps"] else {"name": "VokkApp", "spec": {}}
    lines.extend([
        f"    'name': {app['name']!r},",
        f"    'spec': {json.dumps(app['spec'], indent=4)},",
        "}",
        "",
        "ROUTES = [",
    ])
    for route in parsed["routes"]:
        spec = route["spec"]
        lines.append("    {")
        lines.append(f"        'name': {route['name']!r},")
        lines.append(f"        'method': {_py_list(spec.get('method', 'GET'))},")
        lines.append(f"        'path': {_py_list(spec.get('path', '/'))},")
        lines.append(f"        'auth': {_py_list(spec.get('auth', 'optional'))},")
        lines.append(f"        'action': {_py_list(spec.get('action'))},")
        lines.append("    },")
    lines.extend([
        "]",
        "",
        "STORES = " + json.dumps([{"name": s["name"], **s["spec"]} for s in parsed["stores"]], indent=4),
        "SESSIONS = " + json.dumps([{"name": s["name"], **s["spec"]} for s in parsed["sessions"]], indent=4),
        "ACTIONS = " + json.dumps([{"name": s["name"], **s["spec"]} for s in parsed["actions"]], indent=4),
        "COMPONENTS = " + json.dumps([{"name": s["name"], **s["spec"]} for s in parsed["components"]], indent=4),
    ])
    return "\n".join(lines)


def emit_runtime_client_js(parsed: Dict[str, Any]) -> str:
    routes = []
    for route in parsed["routes"]:
        spec = route["spec"]
        routes.append({
            "name": route["name"],
            "method": spec.get("method", "GET"),
            "path": spec.get("path", "/"),
            "auth": spec.get("auth", "optional"),
            "action": spec.get("action"),
        })
    return (
        "// Generated by VOKK runtime compiler preview\n"
        f"export const vokkRuntimeRoutes = {json.dumps(routes, indent=2)};\n"
    )


def emit_runtime_go(parsed: Dict[str, Any]) -> str:
    lines = [
        "// Generated by VOKK runtime compiler preview",
        "package main",
        "",
        'import "net/http"',
        "",
    ]
    for route in parsed["routes"]:
        spec = route["spec"]
        path = spec.get("path", "/")
        method = str(spec.get("method", "GET")).upper()
        fname = route["name"][0].upper() + route["name"][1:] + "Handler"
        lines.extend([
            f"func {fname}(w http.ResponseWriter, r *http.Request) {{",
            f'    if r.Method != "{method}" {{',
            '        w.WriteHeader(http.StatusMethodNotAllowed)',
            "        return",
            "    }",
            f'    w.Write([]byte("VOKK route: {route["name"]}"))',
            "}",
            "",
        ])
        lines.append(f'// route {method} {path}')
    lines.extend([
        "func main() {",
    ])
    for route in parsed["routes"]:
        spec = route["spec"]
        path = spec.get("path", "/")
        fname = route["name"][0].upper() + route["name"][1:] + "Handler"
        lines.append(f'    http.HandleFunc("{path}", {fname})')
    lines.extend([
        '    http.ListenAndServe(":8080", nil)',
        "}",
    ])
    return "\n".join(lines)


def emit_runtime_java(parsed: Dict[str, Any]) -> str:
    app = parsed["apps"][0]["name"] if parsed["apps"] else "VokkApp"
    lines = [
        "// Generated by VOKK runtime compiler preview",
        "import java.util.List;",
        "",
        f"public class {app}Runtime " + "{",
        "    record RouteSpec(String name, String method, String path, String auth, String action) {}",
        "    static final List<RouteSpec> ROUTES = List.of(",
    ]
    for i, route in enumerate(parsed["routes"]):
        spec = route["spec"]
        comma = "," if i < len(parsed["routes"]) - 1 else ""
        lines.append(
            f'        new RouteSpec("{route["name"]}", "{spec.get("method", "GET")}", "{spec.get("path", "/")}", "{spec.get("auth", "optional")}", "{spec.get("action", "")}"){comma}'
        )
    lines.extend([
        "    );",
        "",
        "    public static void main(String[] args) {",
        '        System.out.println("VOKK runtime preview");',
        "        for (RouteSpec route : ROUTES) {",
        '            System.out.println(route.method() + " " + route.path() + " -> " + route.action());',
        "        }",
        "    }",
        "}",
    ])
    return "\n".join(lines)


def emit_runtime_vokkscript(parsed: Dict[str, Any]) -> str:
    lines: List[str] = []
    for kind in ("apps", "stores", "sessions", "actions", "routes", "components"):
        for item in parsed[kind]:
            block_kind = item["kind"]
            lines.append(f"{block_kind} {item['name']} {{")
            for raw in item["spec"].get("raw_lines", []):
                lines.append(f"  {raw}")
            lines.append("}")
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_runtime_preview(parsed: Dict[str, Any], source: str) -> str:
    app = parsed["apps"][0] if parsed["apps"] else {"name": "VokkApp", "spec": {}}
    rows = []
    for key in ("routes", "stores", "sessions", "actions", "components"):
        rows.append(
            f"<div class='stat'><strong>{parsed['counts'][key]}</strong><span>{html.escape(key)}</span></div>"
        )
    route_cards = []
    for route in parsed["routes"]:
        spec = route["spec"]
        route_cards.append(
            "<div class='card'>"
            f"<strong>{html.escape(route['name'])}</strong>"
            f"<p>{html.escape(str(spec.get('method', 'GET')))} {html.escape(str(spec.get('path', '/')))}</p>"
            f"<p>auth: {html.escape(str(spec.get('auth', 'optional')))}</p>"
            f"<p>action: {html.escape(str(spec.get('action', 'none')))}</p>"
            "</div>"
        )
    if not route_cards:
        route_cards.append("<div class='card'><strong>No routes yet</strong><p>Add `route NAME { method GET path / ... }`.</p></div>")
    py = html.escape(emit_runtime_python(parsed)[:2800])
    go = html.escape(emit_runtime_go(parsed)[:2200])
    java = html.escape(emit_runtime_java(parsed)[:2200])
    vokk = html.escape(emit_runtime_vokkscript(parsed)[:2200])
    return f"""<!doctype html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>VOKK Runtime Preview</title>
<style>
body{{margin:0;background:#0d0f12;color:#efe7dc;font:14px/1.45 Inter,ui-sans-serif,system-ui,sans-serif}}
.wrap{{max-width:1100px;margin:0 auto;padding:24px}}
.hero{{display:flex;justify-content:space-between;gap:24px;align-items:flex-start;padding:20px 0 16px}}
.hero h1{{margin:0 0 6px;font-size:28px}}
.hero p{{margin:0;color:#b7afa4}}
.stats{{display:grid;grid-template-columns:repeat(5,minmax(90px,1fr));gap:10px;margin:14px 0 22px}}
.stat,.card,.panel{{background:#171a1f;border:1px solid rgba(255,255,255,.08);border-radius:10px}}
.stat{{padding:12px;display:grid;gap:4px}}
.stat strong{{font-size:22px}}
.stat span{{color:#b7afa4;text-transform:capitalize}}
.grid{{display:grid;grid-template-columns:1.2fr .8fr;gap:16px}}
.cards{{display:grid;gap:10px}}
.card{{padding:14px}}
.card p{{margin:6px 0 0;color:#c7c0b6}}
.panel{{padding:14px}}
code{{font:12px/1.45 ui-monospace,SFMono-Regular,monospace}}
pre{{margin:0;white-space:pre-wrap;word-break:break-word;font:12px/1.45 ui-monospace,SFMono-Regular,monospace;color:#d7d0c7}}
.muted{{color:#b7afa4}}
</style></head>
<body><div class="wrap">
  <div class="hero">
    <div>
      <div class="muted">VOKK Runtime Preview</div>
      <h1>{html.escape(app['name'])}</h1>
      <p>{html.escape(str(app['spec'].get('title', app['spec'].get('mount', 'Backend surface plan'))))}</p>
    </div>
    <div class="panel"><strong>Reality</strong><pre>This compiles runtime blocks into host plans and generated stubs.
It does not replace the Python host by itself yet.</pre></div>
  </div>
  <div class="stats">{''.join(rows)}</div>
  <div class="grid">
    <div class="cards">{''.join(route_cards)}</div>
    <div class="panel"><strong>Source</strong><pre>{html.escape(source[:5000])}</pre></div>
  </div>
  <div class="grid" style="margin-top:16px">
    <div class="panel"><strong>Python host stub</strong><pre>{py}</pre></div>
    <div class="panel"><strong>Go host stub</strong><pre>{go}</pre></div>
  </div>
  <div class="grid" style="margin-top:16px">
    <div class="panel"><strong>Java host stub</strong><pre>{java}</pre></div>
    <div class="panel"><strong>Normalized VOKK source</strong><pre>{vokk}</pre></div>
  </div>
</div></body></html>"""


def compile_runtime_source(source: str) -> Dict[str, Any]:
    parsed = parse_runtime_source(source)
    return {
        "kind": "runtime",
        "name": parsed["apps"][0]["name"] if parsed["apps"] else "VokkRuntime",
        "parsed": parsed,
        "python": emit_runtime_python(parsed),
        "go": emit_runtime_go(parsed),
        "java": emit_runtime_java(parsed),
        "vokkscript": emit_runtime_vokkscript(parsed),
        "client_js": emit_runtime_client_js(parsed),
        "html": render_runtime_preview(parsed, source),
    }
